---
kind: pipeline
type: docker
name: pipeline1

steps:
- name: say hello
  image: alpine
  commands:
  - echo "hello world"
  
---
kind: pipeline
type: docker
name: pipeline2

steps:
- name: say hello2
  image: alpine
  commands:
  - echo "hello world2"
